# A top-level key for defining PostgreSQL databases
databases:
  - name: recruitapp-db # A unique name for the new database
    plan: free
    region: ohio

# A separate top-level key for all other services
services:
  # Redis is a "service", not a "database"
  - name: recruitapp-redis
    type: redis
    region: ohio
    plan: free
    ipAllowList: []

  # The Django Web Server
  - name: recruitapp-web
    type: web
    runtime: python
    region: ohio
    plan: starter
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
    startCommand: "python manage.py migrate && gunicorn recruitapp_core.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: recruitapp-db # This now correctly refers to the DB in the 'databases' block
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          name: recruitapp-redis
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.13.7"

  # The Celery Background Worker
  - name: recruitapp-worker
    type: worker
    runtime: python
    region: ohio
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A recruitapp_core worker --loglevel=info --concurrency=3"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: recruitapp-db
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          name: recruitapp-redis
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.13.7"