services:
  # 1. The Redis instance for Celery
  - name: recruitapp-redis
    type: redis
    plan: free
    ipAllowList: []

  # 2. The Django Web Server (Gunicorn)
  - name: recruitapp-web
    runtime: python
    type: web
    plan: starter
    # --- FIX: The build command ONLY installs packages ---
    buildCommand: "pip install -r requirements.txt"
    # --- FIX: All Django commands are moved to the start command ---
    startCommand: "python manage.py collectstatic --no-input && python manage.py migrate && gunicorn recruitapp_core.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: recruitapp-db
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: recruitapp-redis
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.13.7"

  # 3. The Celery Background Worker
  - name: recruitapp-worker
    runtime: python
    type: worker
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A recruitapp_core worker --loglevel=info"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: recruitapp-db
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: recruitapp-redis
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.13.7"