services:
  # 1. The Redis instance for Celery
  - name: recruitapp-redis
    type: redis
    plan: free
    # --- FIX: Added required ipAllowList property ---
    ipAllowList: [] # Allows connections from other Render services

  # 2. The Django Web Server (Gunicorn)
  - name: recruitapp-web
    # --- FIX: Changed 'env' to 'runtime' ---
    runtime: python
    type: web
    plan: starter
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
    startCommand: "gunicorn recruitapp_core.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: recruitapp-db # Use the name of your existing Postgres database
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: recruitapp-redis
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.13.7"

  # 3. The Celery Background Worker
  - name: recruitapp-worker
    # --- FIX: Changed 'env' to 'runtime' ---
    runtime: python
    type: worker
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A recruitapp_core worker --loglevel=info"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: recruitapp-db # Use the name of your existing Postgres database
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: recruitapp-redis
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.13.7"