services:
  - name: recruitapp-redis
    type: redis
    plan: free
    ipAllowList: []

  - name: recruitapp-web
    runtime: python
    type: web
    plan: starter
    # --- FIX: Set a build flag and run collectstatic ---
    buildCommand: |
      pip install -r requirements.txt
      export IS_BUILD_PROCESS=true
      python manage.py collectstatic --no-input
    # --- FIX: Only run migrate and gunicorn at start ---
    startCommand: "python manage.py migrate && gunicorn recruitapp_core.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: recruitapp-db
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: recruitapp-redis
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.13.7"

  - name: recruitapp-worker
    runtime: python
    type: worker
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A recruitapp_core worker --loglevel=info"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: recruitapp-db
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: recruitapp-redis
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.13.7"