databases:
  - name: recruitapp-db
    plan: Basic-1gb
    region: oregon

services:
  # Redis is a "service", not a "database"
  - name: recruitapp-redis
    type: redis
    region: oregon
    plan: free
    ipAllowList: []

  # The Django Web Server
  - name: recruitapp-web
    type: web
    runtime: python
    region: oregon
    plan: starter
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
    startCommand: "python manage.py migrate && gunicorn recruitapp_core.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: recruitapp-db
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis 
          name: recruitapp-redis
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.13.7"

  # The Celery Background Worker with Beat Scheduler
  - name: recruitapp-worker
    type: worker
    runtime: python
    region: oregon
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -m celery -A recruitapp_core worker --beat --loglevel=info --concurrency=3"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: recruitapp-db
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: recruitapp-redis
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.13.7"