# Generated by Django 5.2.5 on 2025-09-17 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptcomponent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='promptcomponent',
            name='order',
            field=models.IntegerField(default=0, help_text='Lowest numbers are assembled first.'),
        ),
    ]
