# Generated by Django 5.2.5 on 2025-10-02 17:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0007_sport_playerprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['session', 'timestamp'], name='recruiting__session_35ea8c_idx'),
        ),
    ]
