# Generated by Django 5.2.5 on 2025-10-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0010_chatsession_updated_at_userprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='summary',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
