# Generated by Django 4.2.25 on 2025-10-07 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0011_chatsession_summary'),
        ('recruiting', '0012_update_core_prompt_for_search'),
    ]

    operations = [
    ]
