# Generated by Django 4.2.25 on 2025-10-07 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0013_merge_20251007_0157'),
        ('recruiting', '0014_update_prompt_for_retrieval'),
    ]

    operations = [
    ]
