# Generated by Django 5.2.5 on 2025-10-15 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0016_enhanced_welcome_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('untethered_mode_enabled', models.BooleanField(default=False, help_text='When enabled, removes all topic constraints and persona from the agent')),
                ('can_view_all_user_data', models.BooleanField(default=False)),
                ('can_reset_own_data', models.BooleanField(default=True)),
                ('can_reset_any_user_data', models.BooleanField(default=False)),
                ('can_modify_prompts', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_messages_sent', models.IntegerField(default=0)),
                ('total_agent_responses', models.IntegerField(default=0)),
                ('total_sessions', models.IntegerField(default=0)),
                ('ledger_entries_count', models.IntegerField(default=0)),
                ('action_items_created', models.IntegerField(default=0)),
                ('action_items_completed', models.IntegerField(default=0)),
                ('profile_completion_avg', models.IntegerField(default=0, help_text='Average across all sports')),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('days_since_signup', models.IntegerField(default=0)),
                ('session_count_last_7_days', models.IntegerField(default=0)),
                ('avg_message_length', models.IntegerField(default=0, help_text='Average characters per message')),
                ('searches_triggered', models.IntegerField(default=0, help_text='Times agent used search tool')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
