# Generated by Django 5.2.5 on 2025-10-16 22:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0018_alter_sport_options_alter_sportprofile_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_email', models.EmailField(help_text='Primary contact email for this family account', max_length=254, unique=True)),
                ('secondary_email', models.EmailField(blank=True, help_text='Optional secondary family email', max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription_tier', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('elite', 'Elite')], default='free', max_length=20)),
                ('subscription_status', models.CharField(choices=[('active', 'Active'), ('trial', 'Trial'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
            ],
            options={
                'verbose_name': 'Family Account',
                'verbose_name_plural': 'Family Accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FamilyInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_email', models.EmailField(help_text='Email address of the person being invited', max_length=254)),
                ('invited_role', models.CharField(choices=[('athlete', 'Athlete'), ('parent', 'Parent'), ('guardian', 'Guardian')], max_length=20)),
                ('invited_first_name', models.CharField(blank=True, help_text='First name of invitee (optional)', max_length=100)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('accepted', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Invitation expires after 7 days')),
                ('message', models.TextField(blank=True, help_text='Optional message from inviter to invitee')),
            ],
            options={
                'verbose_name': 'Family Invitation',
                'verbose_name_plural': 'Family Invitations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('athlete', 'Athlete'), ('parent', 'Parent'), ('guardian', 'Guardian'), ('coach', 'Coach')], max_length=20)),
                ('can_edit_profile', models.BooleanField(default=True, help_text='Can edit athlete profiles')),
                ('can_manage_ledger', models.BooleanField(default=True, help_text='Can save/view ledger entries')),
                ('can_manage_actions', models.BooleanField(default=True, help_text='Can create/complete action items')),
                ('can_invite_members', models.BooleanField(default=False, help_text='Can invite other family members (parents only)')),
                ('can_view_chat_history', models.BooleanField(default=False, help_text="Can this member view other members' chat histories? (Future feature)")),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Family Member',
                'verbose_name_plural': 'Family Members',
                'ordering': ['family_account', '-joined_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='actionitem',
            options={'ordering': ['is_complete', 'priority', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='ledgerentry',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='actionitem',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='completed_by',
            field=models.ForeignKey(blank=True, help_text='Who marked this as complete', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Who created this action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='created_by_role',
            field=models.CharField(blank=True, choices=[('athlete', 'Athlete'), ('parent', 'Parent'), ('guardian', 'Guardian')], help_text='Role of the person who saved this entry', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='family_account',
            field=models.ForeignKey(blank=True, help_text='If set, this action is shared with the entire family', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_actions', to='recruiting.familyaccount'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='family_account',
            field=models.ForeignKey(blank=True, help_text='Links session to family for context, but chat remains private', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_chat_sessions', to='recruiting.familyaccount'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='family_account',
            field=models.ForeignKey(blank=True, help_text='If set, this entry is shared with the entire family', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_ledger', to='recruiting.familyaccount'),
        ),
        migrations.AddField(
            model_name='sportprofile',
            name='family_account',
            field=models.ForeignKey(blank=True, help_text='If set, this profile is shared with the entire family', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='athlete_profiles', to='recruiting.familyaccount'),
        ),
        migrations.AddIndex(
            model_name='actionitem',
            index=models.Index(fields=['family_account', 'is_complete', '-created_at'], name='recruiting__family__2ee0de_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['family_account', '-created_at'], name='recruiting__family__2bf054_idx'),
        ),
        migrations.AddField(
            model_name='familyinvitation',
            name='accepted_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='familyinvitation',
            name='family_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='recruiting.familyaccount'),
        ),
        migrations.AddField(
            model_name='familyinvitation',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='familymember',
            name='family_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='recruiting.familyaccount'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='invited_by',
            field=models.ForeignKey(blank=True, help_text='Who invited this member to the family', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_family_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='familymember',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family_membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='familyinvitation',
            index=models.Index(fields=['token'], name='recruiting__token_c78ed4_idx'),
        ),
        migrations.AddIndex(
            model_name='familyinvitation',
            index=models.Index(fields=['invited_email', 'accepted'], name='recruiting__invited_43ec45_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='familymember',
            unique_together={('family_account', 'user')},
        ),
    ]
