# Generated by Django 5.2.5 on 2025-10-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0021_welcome_message_reimagined'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete - moved to deleted section'),
        ),
    ]
