# Generated by Django 5.2.5 on 2025-10-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0022_actionitem_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete - moved to deleted section'),
        ),
    ]
